### ISSUE TITLE
sum_even_fibonacci.cc

### ISSUE THREAD

**Issue by dscheuer1** [MGalloUVM/Group-Exercise#11]
Description: temporary holding variables stores wrong information

Steps to Reproduce

    N/A

Expected Behavior: temporary variable should hold the value stored in b

Actual Behavior: it instead holds the value stored in a

Additional Information

    Operating System: Windows 
    Browser: Firefox
    Version: N/A
    Any other relevant information

Possible Solution: switch temp variable to hold b instead of a

Related Issues Are there any related issues? If so, please link to them here.

Priority How critical is this issue/bug? high priority

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?

Impact What is the impact of this issue/bug? Low, medium, or high?

**Comment by MGalloUVM** [comment]
fixed
