### ISSUE TITLE
rgb_to_hex.py error

### ISSUE THREAD

**Issue by dscheuer1** [MGalloUVM/Group-Exercise#9]
Description: Min color is set to the maximum for this file.

Steps to Reproduce

    N/A

Expected Behavior: minimum color should be 0

Actual Behavior: maximum color should be 255;

Additional Information

    Operating System: Windows
    Browser: Firefox
    Version: N/A
    Any other relevant information

Possible Solution: Change '255' to '0' for the 'r' and 'g' values.

Related Issues Are there any related issues? no

Priority How critical is this issue/bug? medium

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?

Impact What is the impact of this issue/bug? Low, medium, or high?

**Comment by wshayne** [comment]
Fixed, changed minimum values for r and g to 0
